##################### Lab  ####################### 

# Route 1: Create a new lab
###
POST http://localhost:3000/api/v1/lab/add HTTP/1.1
content-type: application/json

{
    "labName": "xxxCity Diagnostic Center  ",
    "labId": 112278,
    "address": "123 Medical Street, Healthcare City",
    "contact1": 10723939836,
    "contact2": 98765432101,
    "email": "contact@citydiagnostic.com",
    "zoneId": "68e3d3b6efbf8e25e1de1c9b",
    "subZoneId":"68e3ec2815f59bd2be28e936",
    "isActive": true
}


# Route 2: Edit lab Data
###
PATCH http://localhost:3000/api/v1/lab/edit HTTP/1.1
content-type: application/json

{
    "_id": "68e54839607459efeb1b026b",
    "labName": "Bubu Dudu Love Story",
    "labId": 111111,
    "address": "123 Medical Street, Healthcare City",
    "contact1": 12345678902,
    "contact2": 98765432000,
    "email": "contact@example.com",
    "zoneId": "68dacb340b6f2cb529c079ca",
    "subZoneId":"68dacb340b6f2cb529c079cb",
    "isActive": true
}

# Route 3: Delete a lab
###
DELETE http://localhost:3000/api/v1/lab/delete HTTP/1.1
content-type: application/json

{
    "_id": "68dacb340b6f2cb529c079ca"
}


# Route 4: Get a lab by labId, email, contact
###
GET http://localhost:3000/api/v1/lab/search HTTP/1.1
content-type: application/json

{
    "field":"zoneId",
    "value": "68dacb340b6f2cb529c079ca"
}

# Route 5: Find All Labs
###
GET http://localhost:3000/api/v1/lab/all HTTP/1.1
content-type: application/json





#################### Zone  ####################### 

# Route 1: Create a zone
###
POST http://localhost:3000/api/v1/labzone/add HTTP/1.1
content-type: application/json

{
    "zoneName": "Chit"
}

# Route 2: Create a subzone
###
POST http://localhost:3000/api/v1/labzone/subzone/add HTTP/1.1
content-type: application/json

{
    "subZoneName": "Goo",
    "zoneId":"68e3d3b6efbf8e25e1de1c9b"
}

# Route 3: Edit a zone name
###
PATCH http://localhost:3000/api/v1/labzone/edit HTTP/1.1
content-type: application/json

{
    "zoneName": "Chio",
    "zoneId": "68e3de076d88bc917e2a69b1"
}

# Route 4: Edit a subzone name
###
PUT http://localhost:3000/api/v1/labzone/subzone/edit HTTP/1.1
content-type: application/json

{
    "subZoneName": "TriX",
    "zoneId": "68e3de076d88bc917e2a69b1",
    "subZoneId" : "68e3de076d88bc917e2a69b1"
}


# Route 5: Delete a zone
###
DELETE http://localhost:3000/api/v1/labzone/delete HTTP/1.1
content-type: application/json

{
    "zoneId": "68e3d715952f3248ccd98378"
}

# Route 6: Delete a sub zone
###
DELETE http://localhost:3000/api/v1/labzone/subzone/delete HTTP/1.1
content-type: application/json

{
    "zoneId": "68e3d3b6efbf8e25e1de1c9b",
    "subZoneId": "68e405c10741cc2f3afca887"

}


# Route 7: Get a zone
###
GET http://localhost:3000/api/v1/labzone HTTP/1.1
content-type: application/json

{
    "zoneId" : "68e3d3b6efbf8e25e1de1c9b"
}

# Route 8: Get all zones
###
GET http://localhost:3000/api/v1/labzone/all HTTP/1.1
content-type: application/json






